# -*- coding: utf-8 -*-
"""Graficos_Visualización

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YeAUggeS0nwYCFfw12w-8bjbzb4LFhX0
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("endometriosis_ml_complete.csv")

print(df.shape)
df.head()

GREEN = "#00A67E"
DARK_GREEN = "#007A5E"
LIGHT_GREEN = "#72C9B2"
SOFT_GREEN = "#BDE8DC"

PINK = "#D96CA6"
LIGHT_PINK = "#F0A5C8"
DARK_PINK = "#C95695"

CREAM = "#F5F1EB"
BLACK = "#222222"

plt.style.use("default")

plt.rcParams["figure.facecolor"] = CREAM
plt.rcParams["axes.facecolor"] = CREAM
plt.rcParams["axes.edgecolor"] = DARK_GREEN
plt.rcParams["axes.labelcolor"] = BLACK
plt.rcParams["xtick.color"] = BLACK
plt.rcParams["ytick.color"] = BLACK
plt.rcParams["text.color"] = BLACK
plt.rcParams["axes.titleweight"] = "bold"
plt.rcParams["font.size"] = 12

output_folder = "graficas_endometriosis"
os.makedirs(output_folder, exist_ok=True)

error_counts = df["error_stage"].value_counts()

plt.figure(figsize=(10, 6))
error_counts.plot(kind="bar", color=GREEN, edgecolor=DARK_GREEN)

plt.title("Distribución de errores diagnósticos por etapa", color=PINK, fontsize=16)
plt.xlabel("Etapa del error diagnóstico", color=BLACK)
plt.ylabel("Número de casos", color=BLACK)
plt.xticks(rotation=45, ha="right")
plt.grid(axis="y", alpha=0.25)

plt.tight_layout()
plt.savefig(f"{output_folder}/01_error_stage.png", dpi=300, facecolor=CREAM)
plt.show()

plt.figure(figsize=(8, 6))
plt.hist(
    df["symptom_burden_score"],
    bins=5,
    color=LIGHT_GREEN,
    edgecolor=DARK_GREEN
)

plt.title("Distribución de la carga total de síntomas", color=PINK, fontsize=16)
plt.xlabel("Número total de síntomas reportados", color=BLACK)
plt.ylabel("Número de casos", color=BLACK)
plt.grid(axis="y", alpha=0.25)

plt.tight_layout()
plt.savefig(f"{output_folder}/02_symptom_burden.png", dpi=300, facecolor=CREAM)
plt.show()

symptom_cols = [col for col in df.columns if col.startswith("sym_")]

symptom_freq = df[symptom_cols].sum().sort_values(ascending=True)

clean_names = {
    "sym_dysmenorrhea": "Dismenorrea",
    "sym_fatigue": "Fatiga",
    "sym_chronic_pelvic_pain": "Dolor pélvico crónico",
    "sym_back_pain": "Dolor lumbar",
    "sym_bloating": "Distensión abdominal",
    "sym_dyspareunia": "Dispareunia",
    "sym_dyschezia": "Disquecia",
    "sym_nausea": "Náusea",
    "sym_menorrhagia": "Menorragia",
    "sym_headache": "Dolor de cabeza"
}

symptom_freq.index = [
    clean_names.get(i, i.replace("sym_", "").replace("_", " ").title())
    for i in symptom_freq.index
]

plt.figure(figsize=(10, 7))
symptom_freq.plot(kind="barh", color=PINK, edgecolor=DARK_PINK)

plt.title("Síntomas más frecuentes en el dataset", color=PINK, fontsize=16)
plt.xlabel("Número de casos", color=BLACK)
plt.ylabel("Síntoma", color=BLACK)
plt.grid(axis="x", alpha=0.25)

plt.tight_layout()
plt.savefig(f"{output_folder}/03_sintomas_frecuentes.png", dpi=300, facecolor=CREAM)
plt.show()

challenge_counts = df["diagnostic_challenge"].value_counts().sort_values()

plt.figure(figsize=(10, 6))

plt.hlines(
    y=challenge_counts.index,
    xmin=0,
    xmax=challenge_counts.values,
    color=LIGHT_GREEN,
    linewidth=4
)

plt.scatter(
    challenge_counts.values,
    challenge_counts.index,
    color=PINK,
    s=180,
    edgecolor=DARK_PINK,
    linewidth=1.5,
    zorder=3
)

for value, category in zip(challenge_counts.values, challenge_counts.index):
    plt.text(
        value + 3,
        category,
        str(value),
        va="center",
        color=BLACK,
        fontsize=11,
        fontweight="bold"
    )

plt.title("Desafíos diagnósticos más frecuentes", color=PINK, fontsize=16)
plt.xlabel("Número de casos", color=BLACK)
plt.ylabel("Desafío diagnóstico", color=BLACK)
plt.grid(axis="x", alpha=0.25)

plt.tight_layout()
plt.savefig(f"{output_folder}/04_diagnostic_challenges_lollipop.png", dpi=300, facecolor=CREAM)
plt.show()

!pip install -q plotly kaleido

import plotly.graph_objects as go

sankey_data = (
    df.groupby(["diagnostic_challenge", "error_stage"])
    .size()
    .reset_index(name="count")
)

sources = list(sankey_data["diagnostic_challenge"].unique())
targets = list(sankey_data["error_stage"].unique())

labels = sources + targets
label_to_id = {label: i for i, label in enumerate(labels)}

source_ids = sankey_data["diagnostic_challenge"].map(label_to_id)
target_ids = sankey_data["error_stage"].map(label_to_id)

node_colors = []
for label in labels:
    if label in sources:
        node_colors.append(GREEN)
    else:
        node_colors.append(PINK)

link_colors = ["rgba(217,108,166,0.35)"] * len(sankey_data)

fig = go.Figure(data=[go.Sankey(
    node=dict(
        pad=18,
        thickness=22,
        line=dict(color=DARK_GREEN, width=0.5),
        label=labels,
        color=node_colors
    ),
    link=dict(
        source=source_ids,
        target=target_ids,
        value=sankey_data["count"],
        color=link_colors
    )
)])

fig.update_layout(
    title_text="Relación entre desafíos diagnósticos y etapa del error",
    font_size=12,
    paper_bgcolor=CREAM,
    plot_bgcolor=CREAM,
    font=dict(color=BLACK)
)

fig.show()

fig.write_html(f"{output_folder}/05_sankey.html")
fig.write_image(f"{output_folder}/05_sankey.png", scale=3)
fig.write_html("05_sankey.html")

fig.write_html("05_sankey.html")

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, ConfusionMatrixDisplay

target = "error_stage"

features = [
    "clinician_type",
    "diagnostic_challenge",
    "pitfall_type",
    "symptom_burden_score",
    "pain_symptom_count",
    "gi_symptom_count",
    "general_symptom_count"
] + symptom_cols

X = df[features]
y = df[target]

categorical_features = ["clinician_type", "diagnostic_challenge", "pitfall_type"]
numeric_features = [col for col in features if col not in categorical_features]

preprocessor = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features),
        ("num", "passthrough", numeric_features)
    ]
)

model = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("classifier", RandomForestClassifier(
        random_state=42,
        class_weight="balanced",
        n_estimators=200
    ))
])

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

model.fit(X_train, y_train)
y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", round(accuracy, 4))
print(classification_report(y_test, y_pred))

fig, ax = plt.subplots(figsize=(10, 8), facecolor=CREAM)

ConfusionMatrixDisplay.from_predictions(
    y_test,
    y_pred,
    xticks_rotation=45,
    cmap="PuRd",
    ax=ax,
    colorbar=True
)

ax.set_title("Matriz de confusión - Random Forest", color=PINK, fontsize=16, fontweight="bold")
ax.set_xlabel("Predicción", color=BLACK)
ax.set_ylabel("Valor real", color=BLACK)

plt.tight_layout()
plt.savefig(f"{output_folder}/06_matriz_confusion_random_forest.png", dpi=300, facecolor=CREAM)
plt.show()

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

pca_features = symptom_cols + [
    "symptom_burden_score",
    "pain_symptom_count",
    "gi_symptom_count",
    "general_symptom_count"
]

X_pca = df[pca_features]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_pca)

pca = PCA(n_components=2)
components = pca.fit_transform(X_scaled)

pca_df = pd.DataFrame(components, columns=["PC1", "PC2"])
pca_df["error_stage"] = df["error_stage"]

palette = [GREEN, PINK, LIGHT_GREEN, LIGHT_PINK, DARK_GREEN, DARK_PINK, SOFT_GREEN]
stages = pca_df["error_stage"].unique()

plt.figure(figsize=(9, 7))

for i, stage in enumerate(stages):
    subset = pca_df[pca_df["error_stage"] == stage]
    plt.scatter(
        subset["PC1"],
        subset["PC2"],
        label=stage,
        alpha=0.75,
        color=palette[i % len(palette)],
        edgecolor="white",
        linewidth=0.4
    )

plt.title("PCA de pacientes según síntomas", color=PINK, fontsize=16)
plt.xlabel(f"PC1 ({pca.explained_variance_ratio_[0]*100:.1f}% varianza)", color=BLACK)
plt.ylabel(f"PC2 ({pca.explained_variance_ratio_[1]*100:.1f}% varianza)", color=BLACK)
plt.grid(alpha=0.25)
plt.legend(bbox_to_anchor=(1.05, 1), loc="upper left")

plt.tight_layout()
plt.savefig(f"{output_folder}/07_pca_sintomas.png", dpi=300, facecolor=CREAM)
plt.show()

print("Varianza explicada:", pca.explained_variance_ratio_)